### ISSUE TITLE
Feature suggestion - time limit on 'open-stream'

### ISSUE THREAD

**Issue by chelliwell** [infostellarinc/stellarcli#122]
Hi. We're planning on a wrapper for the 'satellite open-stream' which will run a CLI process only for the duration of the pass. This could be simplified (for us!!) if open-stream had an optional command line param to "Terminate after XX amount of time" [with a _non_-error exit code].
Do you think that would be a useful option, which would be 'trivial' to add...?
Thanks.

**Comment by davidk81** [comment]
if we implement this, perhaps we should also implement persistent connection retries (until timer is up). @danada how do you feel about this?

should we also take into consideration cases where payload streaming exceeds the pass window (perhaps due to network connectivity issues), should the cli auto-terminate? we should be able to detect when the stream is completed using the last byte marker sent by StarPass.

**Comment by danada** [comment]
I think that if we do add some sort of termination timer it should be a user-provided limit (at least in the first implementation). Like @davidk81 mentioned, there are situations where data can still arrive on the stream after LOS (sometimes even minutes after LOS), so we'll have to be careful how we decide to terminate the stream.

StarPass does indeed send a last message marker, but I don't think this is transmitted between streamer and clients. It might also be possible to automatically terminate the client after no messages are received for some amount of time (5 minutes, for example).

**Comment by chelliwell** [comment]
An option for persistent retries would certainly be useful too, though I suspect I should monitor the process state anyway, in case it has exited for some other reason and needs restarting.
(BTW - currently it doesn't retry if the _first_ connection attempt fails?)
I don't think I'll be getting any indication of the last message. The idea of terminating after no messages for an amount of time is a good one, but it might have some issues for me as our satellite will need to be commanded to start transmission. So this option would be less urgent for me personally.

**Comment by davidk81** [comment]
currently CLI has built-in exponential back-off retry, total retry duration is something like 1min or less. this should be enough for normal use cases, but during our own chaos testing (with simulated server failures), occasionally the CLI is unable to reconnect within the retry duration.

I believe most of our users for the CLI are using external tools to monitor the CLI process, and using the linux `timeout` command to kill the CLI after desired duration.

**Comment by davidk81** [comment]
let's implement `--timeout-seconds` feature. 

- If specified, CLI will exit gracefully (code 0) once timeout reached
- In the event recoverable disconnects happen, CLI should attempt to reconnect until timeout is reached
- It may still be possible for unrecoverable errors to occur, if it does, program should exit with non-zero exit code

**Comment by danada** [comment]
@chelliwell #136 introduced a new feature that should cover this feature suggestion. The new feature accepts a user-provided timestamp that gets compared to the timestamp attached to a message when it is captured at the ground station. This ensures data that continues to arrive after LOS isn't lost even if the provided timestamp = LOS. More usage information is inside the linked issue.

We will be releasing this feature shortly 😄

**Comment by danada** [comment]
Sorry for the delay in updating this issue. We released the time-based auto-close feature back in November 2020: https://github.com/infostellarinc/stellarcli/releases/tag/v0.8.0

We are heading towards a more deterministic way of closing the stream, though, using the LOS event as a trigger to close the CLI. No timeline for this yet, but it is part of our effort to simplify StellarStation usage patterns.
