### ISSUE TITLE
StellarCLI crash after sending a telecommand to the socket

### ISSUE THREAD

**Issue by eraltu** [infostellarinc/stellarcli#13]
StellarCLI seems to crash ocassionally when it receives a telecommand from the UDP socket in proxy mode.
This seems to happen especially if there is a long gap between the issued telecommands. 

### Steps to reproduce
• StellarCLI started with:
`stellar satellite open-stream <SAT_ID>`

• Monitoring of the incoming telemetry with the following command:
`nc -u -l 127.0.0.1 6001 | xxd -c 29`

Telemetry is successfully received like:
 `00004fc: 3230 3138 2d31 302d 3139 5431 393a 3135 3a34 352e 3838 3934 3438 5a00 00  2018-10-19T19:15:45.889448Z..`

• Send command with netcat issued after 5 min of stellarcli running with:
`echo  "0100" | xxd -r -p | nc -u 127.0.0.1 6000`

### Expected Behaviour 
StellarCLI should take the received telecommand and issue it to the infostellar server via grpc.

### Observed Error
• StellarCLI crashes directly after issuing the send command with:
`Error reading from API stream: rpc error: code = Unauthenticated desc = HTTP status code 401`

### Environment / Platform
Linux Centos7
ntp synchronized clock

**Comment by anuraaga** [comment]
Sorry for the delay - we found an issue in the system that can cause the stream to break after five minutes and have rolled out a fix. Please reopen an issue if you see this again. Thanks for reporting!
