### ISSUE TITLE
'Resume' with --output-file

### ISSUE THREAD

**Issue by chelliwell** [infostellarinc/stellarcli#145]
Could I check please whether resuming a stream with '--stream-id' _and with the same_ '--output-file' file name will cause the previous file to be overwritten, or will it append to the file?

**Comment by danada** [comment]
The file will be appended to if it already exists. Here's a link to the docs and the important snippet: https://github.com/infostellarinc/stellarcli/blob/master/docs/stellar_satellite_open-stream.md

> --output-file string          [Alpha feature] The file to write packets to. Creates file if it does not exist; appends to file if it already exists. (default none)
